<?php
/**
 * Recipe
 *
 * PHP version 5
 *
 * @category Class
 * @package  Rakam
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rakam API Documentation
 *
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace client.model;

use \ArrayAccess;

/**
 * Recipe Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Rakam
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Recipe implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Recipe';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'strategy' => 'string',
        'collections' => 'map[string,\client.model\CollectionDefinition]',
        'materialized_views' => '\client.model\MaterializedView[]',
        'continuous_queries' => '\client.model\ContinuousQuery[]'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'strategy' => 'strategy',
        'collections' => 'collections',
        'materialized_views' => 'materialized_views',
        'continuous_queries' => 'continuous_queries'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'strategy' => 'setStrategy',
        'collections' => 'setCollections',
        'materialized_views' => 'setMaterializedViews',
        'continuous_queries' => 'setContinuousQueries'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'strategy' => 'getStrategy',
        'collections' => 'getCollections',
        'materialized_views' => 'getMaterializedViews',
        'continuous_queries' => 'getContinuousQueries'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const STRATEGY_DEFAULT = 'DEFAULT';
    const STRATEGY_SPECIFIC = 'SPECIFIC';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getStrategyAllowableValues()
    {
        return [
            self::STRATEGY_DEFAULT,
            self::STRATEGY_SPECIFIC,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['strategy'] = isset($data['strategy']) ? $data['strategy'] : null;
        $this->container['collections'] = isset($data['collections']) ? $data['collections'] : null;
        $this->container['materialized_views'] = isset($data['materialized_views']) ? $data['materialized_views'] : null;
        $this->container['continuous_queries'] = isset($data['continuous_queries']) ? $data['continuous_queries'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        $allowed_values = array("DEFAULT", "SPECIFIC");
        if (!in_array($this->container['strategy'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'strategy', must be one of #{allowed_values}.";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        $allowed_values = array("DEFAULT", "SPECIFIC");
        if (!in_array($this->container['strategy'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets strategy
     * @return string
     */
    public function getStrategy()
    {
        return $this->container['strategy'];
    }

    /**
     * Sets strategy
     * @param string $strategy
     * @return $this
     */
    public function setStrategy($strategy)
    {
        $allowed_values = array('DEFAULT', 'SPECIFIC');
        if (!in_array($strategy, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'strategy', must be one of 'DEFAULT', 'SPECIFIC'");
        }
        $this->container['strategy'] = $strategy;

        return $this;
    }

    /**
     * Gets collections
     * @return map[string,\client.model\CollectionDefinition]
     */
    public function getCollections()
    {
        return $this->container['collections'];
    }

    /**
     * Sets collections
     * @param map[string,\client.model\CollectionDefinition] $collections
     * @return $this
     */
    public function setCollections($collections)
    {
        $this->container['collections'] = $collections;

        return $this;
    }

    /**
     * Gets materialized_views
     * @return \client.model\MaterializedView[]
     */
    public function getMaterializedViews()
    {
        return $this->container['materialized_views'];
    }

    /**
     * Sets materialized_views
     * @param \client.model\MaterializedView[] $materialized_views
     * @return $this
     */
    public function setMaterializedViews($materialized_views)
    {
        $this->container['materialized_views'] = $materialized_views;

        return $this;
    }

    /**
     * Gets continuous_queries
     * @return \client.model\ContinuousQuery[]
     */
    public function getContinuousQueries()
    {
        return $this->container['continuous_queries'];
    }

    /**
     * Sets continuous_queries
     * @param \client.model\ContinuousQuery[] $continuous_queries
     * @return $this
     */
    public function setContinuousQueries($continuous_queries)
    {
        $this->container['continuous_queries'] = $continuous_queries;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Rakam\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Rakam\ObjectSerializer::sanitizeForSerialization($this));
    }
}


