<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Rakam
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rakam API Documentation
 *
 * An analytics platform API that lets you create your own analytics services.
 *
 * OpenAPI spec version: 0.5
 * Contact: contact@rakam.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Rakam;

use \Rakam\Configuration;
use \Rakam\ApiClient;
use \Rakam\ApiException;
use \Rakam\ObjectSerializer;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Rakam
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createSegment
     *
     * Get events of the user.
     *
     */
    public function testCreateSegment()
    {

    }

    /**
     * Test case for createUser
     *
     * Create new user.
     *
     */
    public function testCreateUser()
    {

    }

    /**
     * Test case for createUsers
     *
     * Create multiple new users.
     *
     */
    public function testCreateUsers()
    {

    }

    /**
     * Test case for getEvents
     *
     * Get events of the user.
     *
     */
    public function testGetEvents()
    {

    }

    /**
     * Test case for getMetadata
     *
     * Get user storage metadata.
     *
     */
    public function testGetMetadata()
    {

    }

    /**
     * Test case for getUser
     *
     * Get user.
     *
     */
    public function testGetUser()
    {

    }

    /**
     * Test case for incrementProperty
     *
     * Set user property.
     *
     */
    public function testIncrementProperty()
    {

    }

    /**
     * Test case for searchUsers
     *
     * Search users.
     *
     */
    public function testSearchUsers()
    {

    }

    /**
     * Test case for setProperties
     *
     * Set user properties.
     *
     */
    public function testSetProperties()
    {

    }

    /**
     * Test case for setPropertiesOnce
     *
     * Set user properties once.
     *
     */
    public function testSetPropertiesOnce()
    {

    }

    /**
     * Test case for unsetProperty
     *
     * Unset user property.
     *
     */
    public function testUnsetProperty()
    {

    }

}
